### ISSUE TITLE
Do sudah deliv di invoice tidak muncul

### ISSUE THREAD

**Issue by muhamadroom** [ThunderID/SKYTECH-MAINTENANCE#11]
![kuyfluvkyitfoh](https://user-images.githubusercontent.com/61110502/76682879-1bdba980-6632-11ea-86cc-756eb76092e6.png)

Do sudah deliv di invoice tidak muncul

**Comment by agilma** [comment]
@muhamadroom Sorry for late respon, utk **DO** yg sudah di **Delivered** akan membuat otomatis kalau type **Invoice Terms** hanya **Immediate** selain type tersebut **Invoice** tidak akan dibuatkan otomatis 😊
![Screenshot_20200322-222621~2](https://user-images.githubusercontent.com/4099329/77253418-a3599600-6c8c-11ea-970f-6fd671d50ad4.png)
