### ISSUE TITLE
Format desimal dibatasi 2 angka dibelakang koma

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/SKYTECH-MAINTENANCE#3]
**Tuliskan Error/Bug**
Tampilan laporan keuangan, journal entry tidak bisa dibaca dengan mudah
Contoh: Harga barang 78.900,999999 rupiah diformat menjadi Rp 98.900.000,99 dst

**Platform / Aplikasi yang bermasalah:**
Dashboard LIVE

**Langkah-langkah error terjadi**
Langkah - langkah error terjadi
1. Masuk halaman finance - report - coa report
2. lihat laporan keuangan dari awal tahun - hari ini

**Hasil yang diharapkan**
Semua yang diformat rupiah, pembulatan 2 angka dibelakang koma

**Screenshots**
![image](https://user-images.githubusercontent.com/5895063/74404002-d32aa800-4e5b-11ea-9f9c-3b2a4bdc67c2.png)

**Comment by agilma** [comment]
https://github.com/erickmo/Skytech-Dashboardv2/commit/030dd1ad1cb0df17a9cf2cb99548b2b66630f74f
