### ISSUE TITLE
Barang tidak bisa dideliver

### ISSUE THREAD

**Issue by muhamadroom** [ThunderID/SKYTECH-MAINTENANCE#5]
**Tuliskan Error/Bug**
setelah ambil data di DO dan akan di delivery menjadi invoice tidak bisa

**Platform / Aplikasi yang bermasalah:**
PC

**Screenshots**
![IMG_20200218_173650](https://user-images.githubusercontent.com/61110502/74729287-cc929b00-5276-11ea-9a74-f3a890e54fa5.jpg)

**Comment by chelsymooy** [comment]
#1
