### ISSUE TITLE
SO Tidak bisa di save

### ISSUE THREAD

**Issue by muhamadroom** [ThunderID/SKYTECH-MAINTENANCE#6]
**Tuliskan Error/Bug**
SO tidak bisa di save pdahal stok masih ada

**Platform / Aplikasi yang bermasalah:**
Contoh: PC

**Screenshots**
![IMG_20200217_194828](https://user-images.githubusercontent.com/61110502/74729604-4b87d380-5277-11ea-9712-b10862b00f62.jpg)

**Comment by agilma** [comment]
@muhamadroom
Untuk barang **Imo Z6 Frozen Edition** tercatat oleh sistem sejumlah **2 stock** dan kebetulan stock tersebut ke **Reserved** di 2 SO yaitu SO nomor **2215** dan **2216** karena status SO masih **Confirmed** terattach foto stock dari barang tersebut.

Stock Product **Imo Z6 Frozen Edition**
![Screen Shot 2020-02-18 at 19 57 38](https://user-images.githubusercontent.com/4099329/74794217-3487c680-52f5-11ea-98cc-cde994b8dd64.png)

Stock ke Reserved di 2 SO
![Screen Shot 2020-02-18 at 19 57 46](https://user-images.githubusercontent.com/4099329/74794236-3f425b80-52f5-11ea-8bfe-4b4427000ef4.png)

**Comment by muhamadroom** [comment]
oke baik terima kasih atas informasi
