### ISSUE TITLE
DO tidak bisa didelivery

### ISSUE THREAD

**Issue by muhamadroom** [ThunderID/SKYTECH-MAINTENANCE#7]
**Tuliskan Error/Bug**
DO tidak bisa didelivery. Sudah dicek untuk stok masih ada semua untuk setiap barang.

**Platform / Aplikasi yang bermasalah:**
Contoh: PC

**Screenshots**
![IMG_20200219_142014](https://user-images.githubusercontent.com/61110502/74811238-aa0a8b80-5323-11ea-9a7c-bd6b72b9b245.jpg)

**Comment by chelsymooy** [comment]
#1
